title: Bruce's blog
description: 不积跬步无以至千里
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Bruce Cheng # add your name
author-img: Bruce.png # add your photo
about-author: 宁静致远. # add description
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: successcw # add your Github handle
#social-linkedin: # add your Linkedin handle
social-email: festival1000@126.com# add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
